MC-38771 add security info for employee
moysklad/api-remap-1.2-doc pull request #221
Opened 2020-12-29 10:42 UTC by segorov12

2021-01-12 08:03 UTC, EReztsov commented on source/includes/_errors.md
> +|43016|Ошибка сброса пароля сотрудника: у пользователя нет или указан не верный email|у пользователя нет или указан не верный email у сотрудника.
У пользователя ... у сотрудника. "У сотрудника, для которого был запрошен сброс пароля, не указан корректный email."

2021-01-12 08:03 UTC, EReztsov commented on source/includes/_errors.md
> +|43019|Ошибка деактивации доступа сотрудника: у данного сотрудника нет доступа к сервису|Пытаемся деактивировать сотрудника, который никогда не был активным.
Лучше заменить "Пытаемся" на "Нельзя"

2021-01-12 08:27 UTC, segorov12 commented on source/includes/_employee.md
> +буду отсутствовать, кроме `view` равное `all` для `currency`, `country` и `uom`. В случае отсутствия поля `permissions` или
поправил

2021-01-12 08:29 UTC, segorov12 commented on source/includes/_employee.md
> +если оно пустое, то будут заданы значения пермиссий по умолчанию.
Поменял на 'если значение поля пустое', обычно если null, то говорят, что не задано

2021-01-12 08:49 UTC, segorov12 commented on source/includes/_employee.md
> +* при отсутствии поле `permissions`, индивидуальные пермисии останутся такими же как были ранее
поправил

2021-01-12 08:50 UTC, segorov12 commented on source/includes/_errors.md
> +|43016|Ошибка сброса пароля сотрудника: у пользователя нет или указан не верный email|у пользователя нет или указан не верный email у сотрудника.
поправил

2021-01-12 08:51 UTC, segorov12 commented on source/includes/_errors.md
> +|43019|Ошибка деактивации доступа сотрудника: у данного сотрудника нет доступа к сервису|Пытаемся деактивировать сотрудника, который никогда не был активным.
поправил

2021-01-12 09:02 UTC, segorov12 commented on source/includes/_employee.md
> +Данные типы имеют следующие поля:
вынес в таблицу

2021-01-15 10:01 UTC, EReztsov commented on source/includes/_employee.md
> +| Название         | Возможные значения | Значение по умолчанию                    | Описание|
Я бы оставил ремарку насчет того, что Значение по умолчанию будет у пермиссии, если не передать список пермиссий вовсе. Иначе может возникнуть недопонимание

2021-01-15 11:39 UTC, segorov12 commented on source/includes/_employee.md
> +то будут заданы значения пермиссий, которые были у сотрудника до смены роли, аналогично ui.
убрал

2021-01-15 11:39 UTC, segorov12 commented on source/includes/_employee.md
> +то будут заданы значения пермиссий, которые были у сотрудника до смены роли, аналогично ui.
убрал

2021-01-15 11:41 UTC, segorov12 commented on source/includes/_employee.md
> +пермисии до смены роли были дефолтные, то произойдет смена роли, иначе будет выведена ошибка об отсутствии пермиссий.
исправил, по поводу кейсов, они приведены пару строчками выше

2021-01-15 11:52 UTC, segorov12 commented on source/includes/_employee.md
> +| Название         | Возможные значения | Значение по умолчанию                    | Описание|
написал

2021-01-29 07:36 UTC, SergeyTru requested changes

2021-01-29 07:36 UTC, SergeyTru commented on CHANGELOG.md
> +- Добавлены новые [эндпоинты для упралвения правами сотрудника]() и [эндпоинты для доступа сотрудника к основному сервису
пропущен url?

2021-01-29 07:36 UTC, SergeyTru commented on source/includes/_changelog.md
> +  - Эндпоинты для [доступа сотрудника к основному сервису МойСклад]()
дважды пропущен url?

2021-01-29 07:36 UTC, SergeyTru commented on source/includes/_employee.md
> +или `Корпоративный`. Для `Пользовательской роли` можно настраивать список пермиссий, заполняя поле `permission`.
Стоит сказать, что если не передавать пермиссии, то будут почти все пермиссии. А если передавать частично, то непереданные будут выключены

2021-01-29 07:36 UTC, SergeyTru commented on source/includes/_employee.md
> +|**viewTurnover**    |Boolean|true|Обороты
Не очень нравится сокращение `Импорт`, `Обороты`
`Импорт`- это импортировать данные из excel и прочего, а
`Обороты` - это просматривать/видеть обороты компании.
Обычно в таблицах сокращают одинаковую часть фразы, а тут - разная.

2021-01-29 07:36 UTC, SergeyTru commented on source/includes/_employee.md
> +Значения в порядке их сужения `own` > `ownShared` > `ownGroup` > `ownGroupShared` > `all`
`ownShared` > `ownGroup` - нет
Егор вчера как раз правил, что они несовместимы

2021-01-29 07:36 UTC, SergeyTru commented on source/includes/_employee.md
> +
Может тут пример привести? Будет проще для понимания.
Например, берём supply. OPERATION означает, что можно настроить **view**, **create**, **update**, **delete**, **approve**, **print**
Например, для view выбираем ownShared. Значит для дочерних ___ можно выбрать только ownShared (на самом деле OWN_SHARED) и own согласно таблице

2021-01-29 07:55 UTC, segorov12 commented on CHANGELOG.md
> +- Добавлены новые [эндпоинты для упралвения правами сотрудника]() и [эндпоинты для доступа сотрудника к основному сервису
вроде нет

2021-01-29 07:55 UTC, segorov12 commented on source/includes/_changelog.md
> +  - Эндпоинты для [доступа сотрудника к основному сервису МойСклад]()
вроде заполнен

2021-01-29 07:59 UTC, segorov12 commented on source/includes/_employee.md
> +или `Корпоративный`. Для `Пользовательской роли` можно настраивать список пермиссий, заполняя поле `permission`.
дополнил, часть перенес

2021-01-29 08:04 UTC, segorov12 commented on source/includes/_employee.md
> +Значения в порядке их сужения `own` > `ownShared` > `ownGroup` > `ownGroupShared` > `all`
это поправлено было ранее

2021-01-29 08:05 UTC, segorov12 commented on source/includes/_employee.md
> +
не уверен, что нужно в примерах и описании это указано

2021-01-29 08:06 UTC, segorov12 commented on source/includes/_employee.md
> +|**viewTurnover**    |Boolean|true|Обороты
импорт, экспорт поправил, обороты, как и остальные идут с префиксом view и соответствуют описанию на ui

2021-02-12 07:55 UTC, SergeyTru approved these changes

2021-02-12 08:03 UTC, merged