MC-55006 добавлено описание для параметра changedSince
moysklad/api-remap-1.2-doc pull request #489
Opened 2022-10-05 12:34 UTC by Vurikus

2022-10-05 18:34 UTC, SergeyTru requested changes

2022-10-05 18:34 UTC, SergeyTru commented on CHANGELOG.md
> +### 05-10-2022
убрать одну решетку

2022-10-05 18:34 UTC, SergeyTru commented on source/includes/reports/_report_stock_current.md
> +Формат - строка вида "гггг-мм-дд чч-мм-сс". Пример значения: `"2016-08-23 15:21:09"`. [Подробнее тут](#mojsklad-json-api-obschie-swedeniq-format-daty-i-wremeni)
пробел надо экранировать (браузер экранирует по умолчанию).
Кстати, ISO `2016-08-23T15:21:09` экранировать не нужно, но, скорее всего, такой формат не распознается

2022-10-05 18:34 UTC, SergeyTru commented on source/includes/reports/_report_stock_current.md
> +- Рекомендуем использовать по формуле не превышающей `3 * интервал` раз (пример: каждую минуту запрашивать остатки за прошедшие три минуты)
для интервалов в 5-10 минут перекрытие в 2 раза достаточно. При опросе раз в час перекрытия в 30 минут достаточно.
Кроме того, иногда нужно проводить полную синхронизацию, иначе сбой может дать ошибку, которая не исправится в будующих дельтах. Хотя бы раз в день.
Идея была в том, что при опросе каждые 5 минут с интервалом в сутки можно получить бан. А разница ДО 3х раз выглядит адекватно. Но это скорее мягкий лимит сверху, а не рекомендация.

2022-10-05 18:34 UTC, SergeyTru commented on source/includes/reports/_report_stock_current.md
> +которые изменились в интервале между временем указанным в параметре `changedSince` и моментом времени - сейчас.
Надо ещё явно написать, что значение будет не на момент `changedSince` и не дельта за период, а текущее фактическое значение. И что `/all/current?changedSince` соберёт со всех складов, но только товары, у которых изменён остаток

2022-10-05 18:37 UTC, SergeyTru commented
Важный момент, который обязательно нужно описать: если удалить товар или склад, мы выводим 0, но запросить этот товар/склад по id уже не получится. Нужно либо хранить соответствие на стороне пользователя либо проводить обратную синхронизацию (перебирать во внешней системе и проверять в МС)

2022-10-06 04:54 UTC, Vurikus commented on CHANGELOG.md
> +### 05-10-2022
сделано

2022-10-06 05:13 UTC, Vurikus commented on source/includes/reports/_report_stock_current.md
> +Формат - строка вида "гггг-мм-дд чч-мм-сс". Пример значения: `"2016-08-23 15:21:09"`. [Подробнее тут](#mojsklad-json-api-obschie-swedeniq-format-daty-i-wremeni)
не понял насчет экранирования пробела. Пример с датой скопирован с этой же доки, там нет никакого экранирования

2022-10-06 05:18 UTC, Vurikus commented on source/includes/reports/_report_stock_current.md
> +- Рекомендуем использовать по формуле не превышающей `3 * интервал` раз (пример: каждую минуту запрашивать остатки за прошедшие три минуты)
что значит полную синхронизацию? Запрашивать долгие остатки? Если мы выдаем не дельту за период, то если был сбой, при следующем запросе мы получим фактический остаток

2022-10-06 05:26 UTC, Vurikus commented on source/includes/reports/_report_stock_current.md
> +которые изменились в интервале между временем указанным в параметре `changedSince` и моментом времени - сейчас.
дополнил

2022-10-06 07:28 UTC, SergeyTru commented on source/includes/reports/_report_stock_current.md
> +- Рекомендуем использовать по формуле не превышающей `3 * интервал` раз (пример: каждую минуту запрашивать остатки за прошедшие три минуты)
полная синхронизация = без `changedSince`.
Например, у пользователя таймер затормозится на секунду (проверки в 12:00:00 и 12:05:01 и интервалом ровно в 5 минут), это изменение уже не будет попадать в новые интервалы и будет потеряно. Понятно, что это не актуально для часто продающихся товаров, но какое-нибудь архивирование товара можно случайно пропустить и больше не увидеть.
Кроме того, хотя мы внимательно проверяли наличие записи, возможны баги, когда изменение потеряно. И поможет только полная синхронизация.

2022-10-06 07:30 UTC, SergeyTru commented on source/includes/reports/_report_stock_current.md
> +не остаток на момент времени `changedSince`, а фактический остаток по номенклатуре у которой изменился остаток за интервал.
по номенклатуре, у которой

2022-10-06 09:24 UTC, Vurikus commented on source/includes/reports/_report_stock_current.md
> +не остаток на момент времени `changedSince`, а фактический остаток по номенклатуре у которой изменился остаток за интервал.
поправил

2022-10-06 10:42 UTC, SergeyTru approved these changes

2022-10-12 07:21 UTC, Vurikus commented on source/includes/reports/_report_stock_current.md
> +- Максимальное значение параметра `changedSince` в прошлое от текущего момента не должно превышать 24 часа 05 минут.
В ошибке в коде поменяли время на 24 часа. Возможно здесь также стоит изменить на 24 часа?

2022-10-12 07:24 UTC, Vurikus commented on source/includes/reports/_report_stock_current.md
> +Важно: если за запрашиваемый интервал был удален (не архивирован) товар или склад, то будет выведен остаток равный 0. Стоит учитывать, что по id запросить этот товар или склад уже не получится.
После последних изменений с zeroLines, текущее описание актуально?

2022-10-13 09:23 UTC, abirman125 commented on source/includes/reports/_report_stock_current.md
> +Важно: если за запрашиваемый интервал был удален (не архивирован) товар или склад, то будет выведен остаток равный 0. Стоит учитывать, что по id запросить этот товар или склад уже не получится.
дописал

2022-10-13 09:23 UTC, abirman125 commented on source/includes/reports/_report_stock_current.md
> +- Максимальное значение параметра `changedSince` в прошлое от текущего момента не должно превышать 24 часа 05 минут.
исправил

2022-10-26 22:35 UTC, merged