Mc 57689
moysklad/api-remap-1.2-doc pull request #520
Opened 2023-01-20 11:35 UTC by IvchenkoAlexandr

2023-01-20 13:13 UTC, SergeyTru requested changes

2023-01-20 13:13 UTC, SergeyTru commented on source/includes/dictionaries/_processingprocess.md
> +### Техпроцесс
давай добавим пустую строку разделитель для удобства чтения

2023-01-20 13:13 UTC, SergeyTru commented on source/includes/dictionaries/_processingprocess.md
> +| **description**  | String(4096)                                              | `=` `!=` `~` `~=` `=~`     | Комментарий Техпроцесса
у нас хватает индексов для поиска по вхождению?

2023-01-20 13:13 UTC, SergeyTru commented on source/includes/dictionaries/_processingprocess.md
> +Позиции Техпроцесса - это список этапов, который входят в техпроцесс. Позиции у техпроцесса может быть от 1 до 100.
"Позиции у техпроцесса может быть от 1 до 100" - переформулировать

2023-01-20 13:13 UTC, SergeyTru commented on source/includes/dictionaries/_processingprocess.md
> +| **limit**  | `number` (optional) **Default: 1000** *Example: 1000* Максимальное количество сущностей для извлечения.`Допустимые значения 1 - 1000`. |
Позиции у техпроцесса может быть от 1 до 100

2023-01-23 06:10 UTC, IvchenkoAlexandr commented on source/includes/dictionaries/_processingprocess.md
> +| **limit**  | `number` (optional) **Default: 1000** *Example: 1000* Максимальное количество сущностей для извлечения.`Допустимые значения 1 - 1000`. |
я ориентировался на "files" - их у файла не может быть больше 100, но при описании limit указано 1000

2023-01-23 06:10 UTC, IvchenkoAlexandr commented on source/includes/dictionaries/_processingprocess.md
> +Позиции Техпроцесса - это список этапов, который входят в техпроцесс. Позиции у техпроцесса может быть от 1 до 100.
"У техпроцесса может быть от 1 до 100 позиций."

2023-01-23 06:10 UTC, IvchenkoAlexandr commented on source/includes/dictionaries/_processingprocess.md
> +| **description**  | String(4096)                                              | `=` `!=` `~` `~=` `=~`     | Комментарий Техпроцесса
Добавил индексы для полей name и externalcode. Для description нет практики добавления такого индекса.

2023-01-23 06:10 UTC, IvchenkoAlexandr commented on source/includes/dictionaries/_processingprocess.md
> +### Техпроцесс
ОК

2023-01-23 09:28 UTC, IvchenkoAlexandr commented on source/includes/dictionaries/_processingprocess.md
> +| **description**  | String(4096)                                              | `=` `!=` `~` `~=` `=~`     | Комментарий Техпроцесса
Удалил индескы и после [обсуждения](https://moysklad.slack.com/archives/C015MF9PQMD/p1674463386821989) с Производством  вынес их создание в отдельный тикет https://lognex.atlassian.net/browse/MC-58936

2023-01-27 06:59 UTC, merged