MC-74782: add field advancePaymentVat in organization
moysklad/api-remap-1.2-doc pull request #738
Opened 2024-10-03 07:03 UTC by dzholdasbek

2024-10-07 05:52 UTC, aziiakaev requested changes

2024-10-07 05:52 UTC, aziiakaev commented on source/includes/dictionaries/_organization.md
> +| **advancePaymentVat** | BigDecimal    |                                                                                                                                                   | Налоговая
что за тип BigDecimal ? Такой тип привязывает к определенному языку, лучше использовать Number. и также добавить информацию что заполнять можно данными из справочника НДС.

2024-10-07 05:52 UTC, aziiakaev commented on source/includes/dictionaries/_organization.md
> +| **advancePaymentVat** | BigDecimal    |                                                                                                                                                   | Налоговая
поля тут все отсортированы, нужно придерживаться этого правила.

2024-10-07 11:38 UTC, dzholdasbek commented on source/includes/dictionaries/_organization.md
> +| **advancePaymentVat** | BigDecimal    |                                                                                                                                                   | Налоговая
поправил

2024-10-16 05:29 UTC, IvchenkoAlexandr commented on source/includes/dictionaries/_organization.md
> +| **advancePaymentVat** | Number        |                                                                                                                                                   | Налоговая
в типах данных https://dev.moysklad.ru/doc/api/remap/1.2/#mojsklad-json-api-obschie-swedeniq-tipy-dannyh не указан такой тип

2024-10-24 08:36 UTC, merged